In [1]:
import pandas as pd
import numpy as np
import pymannkendall as mk
from scipy.stats import spearmanr

In [2]:
data_import = pd.read_csv(r"G:\fresh_start\paper\code_paper\main_data\final_data\station_annual_mean_data.csv")

In [6]:

# for annual

# Initialize a dictionary to store Mann-Kendall results
mann_kendall_results = {}

# Loop through each station
for station in data_import['station'].unique():
    # Filter data for the current station
    df_filtered = data_import[data_import['station'] == station]
    
    # Define columns to test
    selected_columns = ['Tmax', 'Tmin', 'Tavg']
    
    # Perform the Mann-Kendall Trend Test for each column
    for column in selected_columns:
        # Extract the data for the column
        data = df_filtered[column].values
        
        # Perform the Mann-Kendall Trend Test
        result = mk.original_test(data)
        
        # Store the result in the dictionary with a unique key
        key = (station, column)
        mann_kendall_results[key] = {
            'Slope': result.slope,
            'Intercept': result.intercept,
            'Trend': result.trend,
            'P-Value': result.p,
            'Z-Value': result.z,
        }

# Convert results to a DataFrame
results_df = pd.DataFrame(mann_kendall_results).T.reset_index()
results_df.columns = ['Station', 'Column', 'Slope', 'Intercept', 'Trend', 'P-Value', 'Z-Value']

# Print results
print(results_df)

    Station Column     Slope  Intercept       Trend   P-Value   Z-Value
0      1016   Tmax -0.008699  17.072281  decreasing  0.048534 -1.972664
1      1016   Tmin  0.000284   6.055217    no trend  0.985105  0.018669
2      1016   Tavg  0.001034  11.451115    no trend  0.760425  0.304923
3      1024   Tmax -0.040081  24.402423  decreasing  0.000001 -4.884988
4      1024   Tmin -0.017668  12.841757  decreasing  0.000175 -3.752418
..      ...    ...       ...        ...         ...       ...       ...
64     1419   Tmin -0.002662  15.410177    no trend  0.562771 -0.578731
65     1419   Tavg  0.002999  20.717244    no trend  0.466564  0.728081
66     9999   Tmax  0.004005   6.362724  increasing   0.00038  3.553284
67     9999   Tmin  0.003069  -9.794772    no trend  0.096609  1.661518
68     9999   Tavg  0.003282  -1.722658  increasing  0.002544  3.018114

[69 rows x 7 columns]

In [7]:
#results_df.to_csv(r"G:\fresh_start\paper\code_paper\main_data\final_data\annual_mannkendal_results.csv", index=False)

In [4]:
data_import_seasonal = pd.read_csv(r"G:\fresh_start\paper\code_paper\main_data\final_data\station_seasonal_mean_data.csv")

In [5]:
data_import_seasonal

,year,season,station,lat,long,elevation,Tmin,Tmax,Tavg
0,1962,Monsoon,1016,27.944561,85.595136,2574.0,12.501749,21.143855,16.822802
1,1962,Monsoon,1024,27.616117,85.565503,1543.0,19.203249,27.845355,23.524302
2,1962,Monsoon,1036,27.645134,85.620881,857.0,23.662249,32.304355,27.983302
3,1962,Monsoon,1103,27.630447,86.232114,1877.0,17.032249,25.674355,21.353302
4,1962,Monsoon,1123,27.394703,86.061233,497.0,26.002249,34.644355,30.323302
...,...,...,...,...,...,...,...,...,...
5607,2022,Winter,1327,27.391062,87.204384,1064.0,9.833333,20.356522,15.094927
5608,2022,Winter,1401,27.683330,87.783330,3119.0,-4.210576,8.001987,1.895705
5609,2022,Winter,1405,27.358611,87.670000,1744.0,5.282222,15.416120,10.349171
5610,2022,Winter,1419,27.143674,87.765595,1157.0,7.908889,21.526293,14.717591
5611,2022,Winter,9999,27.961111,86.808889,5200.0,-13.829208,1.179860,-6.324674

In [ ]:
# for annual

# Initialize a dictionary to store Mann-Kendall results
mann_kendall_results = {}

for season in data_import["season"].unique():
# Loop through each station
for station in data_import['station'].unique():
    # Filter data for the current station
    df_filtered = data_import[data_import['station'] == station]
    
    # Define columns to test
    selected_columns = ['Tmax', 'Tmin', 'Tavg']
    
    # Perform the Mann-Kendall Trend Test for each column
    for column in selected_columns:
        # Extract the data for the column
        data = df_filtered[column].values
        
        # Perform the Mann-Kendall Trend Test
        result = mk.original_test(data)
        
        # Store the result in the dictionary with a unique key
        key = (station, column)
        mann_kendall_results[key] = {
            'Slope': result.slope,
            'Intercept': result.intercept,
            'Trend': result.trend,
            'P-Value': result.p,
            'Z-Value': result.z,
        }

# Convert results to a DataFrame
results_df = pd.DataFrame(mann_kendall_results).T.reset_index()
results_df.columns = ['Station', 'Column', 'Slope', 'Intercept', 'Trend', 'P-Value', 'Z-Value']