In [22]:
import pandas as pd
import numpy as np

In [23]:
data_import = pd.read_csv(r"G:\fresh_start\paper\code_paper\main_data\final_data\1962_lapse_station_data.csv")
data_import["Tavg"] = (data_import['Tmax']+data_import["Tmin"])/2

In [14]:
#data_import.to_csv(r"G:\fresh_start\paper\code_paper\main_data\final_data\daily_avg_1962.csv", index=False)

In [24]:
data_import['date'] = pd.to_datetime(data_import['date'])
data_import['year'] = data_import['date'].dt.year

In [25]:
annual_regional_df = data_import.groupby([ 'year', 'regions', 'lat', 'long', 'elevation']).agg({
    'Tmin': 'min',
    'Tmax': 'max',
    'Tavg': 'mean'
}).reset_index()

In [26]:
annual_regional_df

,year,regions,lat,long,elevation,Tmin,Tmax,Tavg
0,1962,High Mountain,27.683330,87.783330,3119.0,-6.300000,21.000000,7.875205
1,1962,High Mountain,27.816670,86.716670,3450.0,-7.422254,18.146734,6.419072
2,1962,High Mountain,27.816670,86.716670,3700.0,-9.047254,16.521734,4.794072
3,1962,High Mountain,27.833330,86.766670,3857.0,-10.067754,15.501234,3.773572
4,1962,High Mountain,27.961111,86.808889,5200.0,-15.283419,11.761102,-1.605004
...,...,...,...,...,...,...,...,...
1398,2022,Hill,27.645134,85.620881,857.0,2.800000,34.325294,21.936899
1399,2022,Middle Mountain,27.505118,86.586215,2383.0,-1.000000,30.500000,16.285220
1400,2022,Middle Mountain,27.944561,85.595136,2574.0,-4.900000,23.500000,12.626625
1401,2022,Siwalik,26.730538,86.934812,101.0,6.700000,38.700000,25.051994
1402,2022,Tarai,26.820440,87.159170,105.0,12.114045,39.213294,28.044042

In [27]:
#annual_regional_df.to_csv(r"G:\fresh_start\paper\code_paper\main_data\01_new_data\regional_annual_extreme_data.csv", index=False)

In [28]:
data_import['month'] = data_import['date'].dt.month
# Define a function to adjust the year for the winter season
def adjust_year(row):
    if row['month'] == 12:
        return row['year'] + 1
    return row['year']

# Apply the function to create the adjusted year column
data_import['adjusted_year'] = data_import.apply(adjust_year, axis=1)
# Define a function to map months to seasons
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Premonsoon'
    elif month in [6, 7, 8, 9]:
        return 'Monsoon'
    elif month in [10, 11]:
        return 'Postmonsoon'
    else:
        return None

# Apply the function to create the season column
data_import['season'] = data_import['month'].apply(get_season)

In [29]:
# Group by year and season and calculate the mean for Tmin and Tmax
seasonal_extreme_df = data_import.groupby([  'year','regions', 'season','lat', 'long', 'elevation']).agg({
    'Tmin': 'min',
    'Tmax': 'max',
    'Tavg': 'mean'
}).reset_index()

# Print the resulting DataFrame
print(seasonal_extreme_df)

      year        regions       season        lat       long  elevation  \
0     1962  High Mountain      Monsoon  27.683330  87.783330     3119.0
1     1962  High Mountain      Monsoon  27.816670  86.716670     3450.0
2     1962  High Mountain      Monsoon  27.816670  86.716670     3700.0
3     1962  High Mountain      Monsoon  27.833330  86.766670     3857.0
4     1962  High Mountain      Monsoon  27.961111  86.808889     5200.0
...    ...            ...          ...        ...        ...        ...
5607  2022        Siwalik       Winter  26.730538  86.934812      101.0
5608  2022          Tarai      Monsoon  26.820440  87.159170      105.0
5609  2022          Tarai  Postmonsoon  26.820440  87.159170      105.0
5610  2022          Tarai   Premonsoon  26.820440  87.159170      105.0
5611  2022          Tarai       Winter  26.820440  87.159170      105.0

           Tmin       Tmax       Tavg
0      5.900000  21.000000  12.639344
1      2.909834  18.146734  11.128802
2      1.284834  16.521734   9.503802
3      0.264334  15.501234   8.483302
4    -14.804998  11.688302   2.967843
...         ...        ...        ...
5607   6.700000  29.600000  18.174751
5608  26.086548  39.213294  32.175812
5609  17.533250  38.026159  27.138211
5610  17.403583  38.276447  29.580348
5611  12.114045  30.896535  21.486705

[5612 rows x 9 columns]

In [30]:
seasonal_avg_df.to_csv(r"G:\fresh_start\paper\code_paper\main_data\01_new_data\regional_seasonal_extreme_data.csv", index=False)