In [1]:
import pandas as pd
import scipy.stats 
import pymannkendall as mk

### For monthly

In [2]:
primary_etccdi_data = pd.read_excel('G:/fresh_start/main_thesis/data/saved_data/etccdi_climate_indices.xlsx')
#etccdi_season_result_df

In [3]:
print(primary_etccdi_data)

     Geo_region  Year  Month        TNn        TNx        TXn        TXx  \
0          Hill  1990      1  -8.939842  15.196031   3.463189  27.000000
1          Hill  1990      2   0.500000  12.356745   3.267721  25.500000
2          Hill  1990      3   0.700000  17.825521   7.099203  30.000000
3          Hill  1990      4   4.753237  20.176975  14.400000  39.611019
4          Hill  1990      5  10.400000  22.800000  19.500000  36.509515
...         ...   ...    ...        ...        ...        ...        ...
1183      Terai  2022      8  20.600000  27.900000  28.100000  35.700000
1184      Terai  2022      9  18.800000  26.500000  27.200000  34.600000
1185      Terai  2022     10  16.500000  25.000000  26.900000  35.000000
1186      Terai  2022     11  13.400000  18.000000  27.500000  32.500000
1187      Terai  2022     12   8.500000  13.600000  18.825789  29.600000

         TN10p     TN90p     TX10p     TX90p
0     0.100000  0.093548  0.100000  0.100000
1     0.100000  0.100000  0.100000  0.096429
2     0.083871  0.100000  0.100000  0.100000
3     0.083333  0.096667  0.100000  0.096667
4     0.096774  0.100000  0.100000  0.100000
...        ...       ...       ...       ...
1183  0.096774  0.096774  0.096774  0.096774
1184  0.100000  0.066667  0.100000  0.100000
1185  0.064516  0.096774  0.096774  0.096774
1186  0.100000  0.100000  0.100000  0.100000
1187  0.096774  0.096774  0.096774  0.096774

[1188 rows x 11 columns]

In [11]:
import pandas as pd
import pymannkendall as mk

# Assuming you have your data in a DataFrame called primary_etccdi_data

# Create an empty list to store the results as dictionaries
results_list = []

# Get unique Geo_regions
unique_regions = primary_etccdi_data['Geo_region'].unique()
unique_months = primary_etccdi_data['Month'].unique()
# Get the temperature indices you want to test
temperature_indices = ['TNn', 'TNx', 'TXn', 'TXx', 'TN10p', 'TN90p', 'TX10p', 'TX90p']

# Loop through each Geo_region and temperature index
for month in unique_months:
  for region in unique_regions:
      for index in temperature_indices:
          # Filter data for the current region and index
          
          filtered_data = primary_etccdi_data[(primary_etccdi_data['Geo_region'] == region) & (primary_etccdi_data['Month'] == month)]

          # Perform the Mann-Kendall test
          result = mk.original_test(filtered_data[index], alpha=0.05)
          
          # Append the results to the list as a dictionary
          results_list.append({
              'Geo_region': region,
              'Month' : month,
              'Index': index,
              'Slope': result.slope,
              'Intercept': result.intercept,
              'Trend': result.trend,
              'P-Value': result.p,
              'Z-Value': result.z
          })

# Convert the list of dictionaries into a DataFrame
results_df = pd.DataFrame(results_list)

# Now, results_df contains the test results for each Geo_region and temperature index
print(results_df)

    Geo_region  Month  Index     Slope  Intercept       Trend   P-Value  \
0         Hill      1    TNn  0.021648  -0.246361    no trend  0.409726
1         Hill      1    TNx  0.037151  11.405581    no trend  0.251382
2         Hill      1    TXn  0.126832   7.370691  increasing  0.001256
3         Hill      1    TXx  0.039497  25.868050    no trend  0.097069
4         Hill      1  TN10p -0.000196   0.096679    no trend  0.073916
..         ...    ...    ...       ...        ...         ...       ...
283      Terai     12    TXx -0.043739  30.699826    no trend  0.219523
284      Terai     12  TN10p  0.000000   0.096774    no trend  0.734942
285      Terai     12  TN90p  0.000000   0.096774    no trend  0.458820
286      Terai     12  TX10p  0.000000   0.096774    no trend  0.521812
287      Terai     12  TX90p  0.000000   0.096774    no trend  0.301932

      Z-Value
0    0.824377
1    1.147000
2    3.225808
3    1.659230
4   -1.787134
..        ...
283 -1.227798
284  0.338559
285  0.740791
286  0.640555
287  1.032299

[288 rows x 8 columns]

In [12]:
results_df.to_csv('G:/fresh_start/main_thesis/data/saved_data/etccdi_monthly_trend_final.csv')

### For Seasonal

In [5]:
for_seasonal_work = pd.read_csv('G:/fresh_start/main_thesis/data/work_data/etccdi_season_result_df.csv')

In [6]:
for_seasonal_work

,Unnamed: 0,Geo_region,Year,Season,TNn,TNx,TXn,TXx,TN10p,TN90p,TX10p,TX90p
0,0,Hill,1990,Winter,-8.939842,15.196031,3.267721,28.500000,0.100000,0.095556,0.098889,0.097778
1,1,Hill,1990,Premonsoon,0.700000,22.800000,7.099203,39.611019,0.100000,0.096739,0.090217,0.100000
2,2,Hill,1990,Monsoon,13.225000,26.557076,17.300000,40.441107,0.086066,0.100000,0.100000,0.090984
3,3,Hill,1990,Postmonsoon,6.000000,22.523423,9.408605,36.475174,0.100000,0.100000,0.100000,0.100000
4,4,Hill,1991,Winter,-2.081612,15.388686,5.911761,28.500000,0.095556,0.100000,0.100000,0.100000
...,...,...,...,...,...,...,...,...,...,...,...,...
391,391,Terai,2021,Postmonsoon,13.500000,25.400000,26.400000,36.200000,0.081967,0.098361,0.098361,0.098361
392,392,Terai,2022,Winter,6.700000,15.700000,16.399842,29.600000,0.100000,0.088889,0.100000,0.066667
393,393,Terai,2022,Premonsoon,12.400000,26.500000,26.200000,38.700000,0.108696,0.097826,0.108696,0.076087
394,394,Terai,2022,Monsoon,16.900000,27.900000,25.700000,35.700000,0.106557,0.090164,0.098361,0.098361
395,395,Terai,2022,Postmonsoon,13.400000,25.000000,26.900000,35.000000,0.098361,0.098361,0.098361,0.098361

In [7]:
season_result_df

NameError: name 'season_result_df' is not defined

In [9]:

season_results_list = []

# Get unique Geo_regions
unique_regions = for_seasonal_work['Geo_region'].unique()
unique_seasons = for_seasonal_work['Season'].unique()
# Get the temperature indices you want to test
temperature_indices = ['TNn', 'TNx', 'TXn', 'TXx', 'TN10p', 'TN90p', 'TX10p', 'TX90p']

# Loop through each Geo_region and temperature index
for season in unique_seasons:
  for region in unique_regions:
      for index in temperature_indices:
          # Filter data for the current region and index
          filtered_data = for_seasonal_work[(for_seasonal_work['Geo_region'] == region) & (for_seasonal_work['Season'] == season)]

          #filtered_data = for_seasonal_work[(for_seasonal_work['Geo_region'] == region)]
          # Perform the Mann-Kendall test
          result = mk.original_test(filtered_data[index], alpha=0.05)
          
          # Append the results to the list as a dictionary
          season_results_list.append({
              'Geo_region': region,
              'Season' : season,
              'Index': index,
              'Slope': result.slope,
              'Intercept': result.intercept,
              'Trend': result.trend,
              'P-Value': result.p,
              'Z-Value': result.z
          })

# Convert the list of dictionaries into a DataFrame
season_results_df = pd.DataFrame(season_results_list)

# Now, results_df contains the test results for each Geo_region and temperature index
print(season_results_df)

   Geo_region       Season  Index     Slope  Intercept       Trend   P-Value  \
0        Hill       Winter    TNn  0.016026  -0.256410    no trend  0.630612
1        Hill       Winter    TNx  0.007959  15.172658    no trend  0.721413
2        Hill       Winter    TXn  0.066667   7.433333  increasing  0.045321
3        Hill       Winter    TXx  0.128425  27.852702  increasing  0.001387
4        Hill       Winter  TN10p -0.000100   0.097202    no trend  0.234706
..        ...          ...    ...       ...        ...         ...       ...
91      Terai  Postmonsoon    TXx -0.001376  36.022024    no trend  0.803718
92      Terai  Postmonsoon  TN10p  0.000000   0.098361    no trend  0.675138
93      Terai  Postmonsoon  TN90p  0.000000   0.098361    no trend  0.522584
94      Terai  Postmonsoon  TX10p  0.000000   0.098361    no trend  0.822892
95      Terai  Postmonsoon  TX90p  0.000000   0.098361    no trend  0.153931

     Z-Value
0   0.480866
1   0.356571
2   2.001665
3   3.197355
4  -1.188322
..       ...
91 -0.248538
92 -0.419107
93  0.639367
94 -0.223827
95  1.425782

[96 rows x 8 columns]

season_results_df.to_csv('G:/fresh_start/main_thesis/data/final_datas/pymannkendal_seasonal_trend.csv')

### For annual

In [ ]:
for_yearly_work = pd.read_excel('G:/fresh_start/main_thesis/data/final_datas/etccdi_yearly_result_df.xlsx')

In [ ]:

yearly_results_list = []

# Get unique Geo_regions
unique_regions = for_yearly_work['Geo_region'].unique()

# Get the temperature indices you want to test
temperature_indices = ['TNn', 'TNx', 'TXn', 'TXx', 'TN10p', 'TN90p', 'TX10p', 'TX90p']

# Loop through each Geo_region and temperature index

for region in unique_regions:
      for index in temperature_indices:
          # Filter data for the current region and index
          filtered_data = for_yearly_work[(for_yearly_work['Geo_region'] == region)]
          # Perform the Mann-Kendall test
          result = mk.original_test(filtered_data[index], alpha=0.05)
          
          # Append the results to the list as a dictionary
          yearly_results_list.append({
              'Geo_region': region,
              
              'Index': index,
              'Slope': result.slope,
              'Intercept': result.intercept,
              'Trend': result.trend,
              'P-Value': result.p,
              'Z-Value': result.z
          })

# Convert the list of dictionaries into a DataFrame
yearly_results_df = pd.DataFrame(yearly_results_list)

# Now, results_df contains the test results for each Geo_region and temperature index
print(yearly_results_df)

   Geo_region  Index     Slope  Intercept       Trend   P-Value   Z-Value
0        Hill    TNn  0.026102  -0.717631    no trend  0.475563  0.713457
1        Hill    TNx -0.050600  28.877709    no trend  0.132633 -1.503801
2        Hill    TXn  0.063082   7.490684    no trend  0.124499  1.536161
3        Hill    TXx -0.121350  43.820745  decreasing  0.002466 -3.027473
4        Hill  TN10p -0.000067   0.099972  decreasing  0.040605 -2.047542
5        Hill  TN90p -0.000048   0.099668    no trend  0.118912 -1.559358
6        Hill  TX10p -0.000018   0.099474    no trend  0.113590 -1.582260
7        Hill  TX90p  0.000137   0.096986    no trend  0.072263  1.797460
8    Mountain    TNn  0.141258  -9.876038  increasing  0.000581  3.440173
9    Mountain    TNx  0.006740  23.410662    no trend  0.816215  0.232416
10   Mountain    TXn  0.048450   3.824793    no trend  0.420243  0.806000
11   Mountain    TXx  0.020196  33.176866    no trend  0.494720  0.682821
12   Mountain  TN10p -0.000024   0.100196  decreasing  0.026965 -2.212028
13   Mountain  TN90p -0.000098   0.101370  decreasing  0.003760 -2.897592
14   Mountain  TX10p -0.000039   0.100544  decreasing  0.016924 -2.388360
15   Mountain  TX90p -0.000079   0.100290  decreasing  0.024664 -2.246620
16      Terai    TNn  0.038904   4.351350    no trend  0.263771  1.117522
17      Terai    TNx  0.004583  27.526667    no trend  0.460743  0.737624
18      Terai    TXn  0.080122  18.478349    no trend  0.167792  1.379334
19      Terai    TXx -0.001747  39.427951    no trend  0.925862 -0.093052
20      Terai  TN10p  0.000130   0.099012  increasing  0.023502  2.265176
21      Terai  TN90p -0.000040   0.093797    no trend  0.349851 -0.934879
22      Terai  TX10p  0.000000   0.098630    no trend  0.436912 -0.777419
23      Terai  TX90p  0.000000   0.093151    no trend  0.900824  0.124620

In [ ]:
yearly_results_df.to_excel('G:/fresh_start/main_thesis/data/final_datas/pymannkendal_yearly_trend.xlsx')